# Generated by Django 5.0.3 on 2024-09-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('admission_no', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(max_length=300)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
